apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3vrc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-3vrc@sha256:c1bc1f2742f613a399cc5c0b2e17b773a7e825a8eb466bf4bb071cbd6677f9db
        name: my-nodejs
        resources: {}
status: {}
